"""MAC address OUI vendor lookup.

Contains a built-in table of ~200 common consumer/enterprise OUI prefixes.
Falls back to 'Unknown' for MACs not in the table.  The table covers the
most commonly seen vendors on residential and small-business networks:
phones, tablets, laptops, IoT gear, smart-home devices, and networking
equipment.
"""
from __future__ import annotations

# OUI prefix → vendor name.  Keys are uppercase, colon-separated, first 3
# octets (e.g. "AA:BB:CC").
_OUI_TABLE: dict[str, str] = {
    # ── Apple ────────────────────────────────────────────────────────
    "00:1C:B3": "Apple",
    "00:25:00": "Apple",
    "00:26:08": "Apple",
    "00:26:B0": "Apple",
    "00:26:BB": "Apple",
    "28:CF:E9": "Apple",
    "2C:F0:A2": "Apple",
    "30:35:AD": "Apple",
    "3C:15:C2": "Apple",
    "3C:E0:72": "Apple",
    "40:33:1A": "Apple",
    "48:E7:DA": "Apple",
    "54:26:96": "Apple",
    "58:55:CA": "Apple",
    "5C:F7:E6": "Apple",
    "60:FE:C5": "Apple",
    "64:70:33": "Apple",
    "70:DE:E2": "Apple",
    "74:E2:F5": "Apple",
    "78:7E:61": "Apple",
    "80:E6:50": "Apple",
    "84:FC:FE": "Apple",
    "88:66:A5": "Apple",
    "8C:85:90": "Apple",
    "90:8D:6C": "Apple",
    "98:01:A7": "Apple",
    "9C:20:7B": "Apple",
    "A4:D1:D2": "Apple",
    "A8:51:AB": "Apple",
    "AC:87:A3": "Apple",
    "B0:34:95": "Apple",
    "B8:53:AC": "Apple",
    "BC:52:B7": "Apple",
    "C0:B6:58": "Apple",
    "C8:69:CD": "Apple",
    "CC:08:8D": "Apple",
    "D0:C5:F3": "Apple",
    "D4:61:9D": "Apple",
    "DC:A4:CA": "Apple",
    "E0:C7:67": "Apple",
    "E4:CE:8F": "Apple",
    "F0:18:98": "Apple",
    "F4:31:C3": "Apple",
    "F8:FF:C2": "Apple",
    # ── Samsung ──────────────────────────────────────────────────────
    "00:07:AB": "Samsung",
    "00:12:FB": "Samsung",
    "00:15:99": "Samsung",
    "00:16:32": "Samsung",
    "00:17:D5": "Samsung",
    "00:1A:8A": "Samsung",
    "00:21:19": "Samsung",
    "00:23:39": "Samsung",
    "00:24:54": "Samsung",
    "00:26:37": "Samsung",
    "08:08:C2": "Samsung",
    "14:49:E0": "Samsung",
    "18:3A:2D": "Samsung",
    "1C:66:AA": "Samsung",
    "28:98:7B": "Samsung",
    "30:96:FB": "Samsung",
    "38:01:95": "Samsung",
    "40:4E:36": "Samsung",
    "50:01:D9": "Samsung",
    "54:92:BE": "Samsung",
    "58:C3:8B": "Samsung",
    "6C:F3:73": "Samsung",
    "78:BD:BC": "Samsung",
    "84:11:9E": "Samsung",
    "8C:77:12": "Samsung",
    "94:35:0A": "Samsung",
    "A0:82:1F": "Samsung",
    "AC:5F:3E": "Samsung",
    "B4:79:A7": "Samsung",
    "BC:72:B1": "Samsung",
    "C4:50:06": "Samsung",
    "CC:07:AB": "Samsung",
    "D0:22:BE": "Samsung",
    "E4:7C:F9": "Samsung",
    "F0:25:B7": "Samsung",
    "F8:04:2E": "Samsung",
    # ── Google / Nest ────────────────────────────────────────────────
    "08:9E:08": "Google",
    "1C:F2:9A": "Google",
    "30:FD:38": "Google",
    "3C:5A:B4": "Google",
    "44:07:0B": "Google",
    "48:D6:D5": "Google",
    "54:60:09": "Google",
    "5C:E5:0C": "Google",
    "6C:AD:F8": "Google",
    "94:EB:2C": "Google",
    "A4:77:33": "Google",
    "B0:E4:D5": "Google",
    "F4:F5:D8": "Google",
    "F4:F5:E8": "Google",
    "18:B4:30": "Nest Labs",
    "64:16:66": "Nest Labs",
    # ── Amazon / Ring / Echo ─────────────────────────────────────────
    "00:FC:8B": "Amazon",
    "0C:47:C9": "Amazon",
    "10:CE:A9": "Amazon",
    "14:91:82": "Amazon",
    "18:74:2E": "Amazon",
    "34:D2:70": "Amazon",
    "38:F7:3D": "Amazon",
    "40:A2:DB": "Amazon",
    "44:65:0D": "Amazon",
    "48:E6:C0": "Amazon",
    "4C:EF:C0": "Amazon",
    "50:DC:E7": "Amazon",
    "68:37:E9": "Amazon",
    "6C:56:97": "Amazon",
    "74:C2:46": "Amazon",
    "84:D6:D0": "Amazon",
    "8C:49:62": "Amazon",
    "A0:02:DC": "Amazon",
    "AC:63:BE": "Amazon",
    "B0:FC:0D": "Amazon",
    "B4:7C:9C": "Amazon",
    "CC:F7:35": "Amazon",
    "F0:F0:A4": "Amazon",
    "FC:65:DE": "Amazon",
    # ── Microsoft / Xbox ─────────────────────────────────────────────
    "00:15:5D": "Microsoft (Hyper-V)",
    "00:17:FA": "Microsoft",
    "00:1D:D8": "Microsoft",
    "00:50:F2": "Microsoft",
    "28:18:78": "Microsoft",
    "58:82:A8": "Microsoft",
    "60:45:BD": "Microsoft",
    "7C:1E:52": "Microsoft",
    "98:5F:D3": "Microsoft",
    "B4:0E:DE": "Microsoft",
    "C8:3F:26": "Microsoft",
    # ── Intel ────────────────────────────────────────────────────────
    "00:1B:21": "Intel",
    "00:1E:64": "Intel",
    "00:1E:67": "Intel",
    "00:1F:3B": "Intel",
    "3C:97:0E": "Intel",
    "48:51:B7": "Intel",
    "5C:87:9C": "Intel",
    "68:05:CA": "Intel",
    "80:86:F2": "Intel",
    "8C:8D:28": "Intel",
    "A4:C3:F0": "Intel",
    "B4:96:91": "Intel",
    "C8:D9:D2": "Intel",
    # ── Dell ─────────────────────────────────────────────────────────
    "00:08:74": "Dell",
    "00:14:22": "Dell",
    "18:03:73": "Dell",
    "24:6E:96": "Dell",
    "34:17:EB": "Dell",
    "B0:83:FE": "Dell",
    "D4:BE:D9": "Dell",
    "F0:1F:AF": "Dell",
    "F8:BC:12": "Dell",
    # ── HP / HPE ─────────────────────────────────────────────────────
    "00:0D:9D": "HP",
    "00:14:38": "HP",
    "00:1B:78": "HP",
    "00:1E:0B": "HP",
    "00:21:5A": "HP",
    "00:25:B3": "HP",
    "10:60:4B": "HP",
    "28:92:4A": "HP",
    "3C:D9:2B": "HP",
    "80:C1:6E": "HP",
    "D8:D3:85": "HP",
    # ── Ubiquiti ─────────────────────────────────────────────────────
    "00:27:22": "Ubiquiti",
    "04:18:D6": "Ubiquiti",
    "18:E8:29": "Ubiquiti",
    "24:5A:4C": "Ubiquiti",
    "24:A4:3C": "Ubiquiti",
    "44:D9:E7": "Ubiquiti",
    "68:72:51": "Ubiquiti",
    "70:A7:41": "Ubiquiti",
    "74:83:C2": "Ubiquiti",
    "78:8A:20": "Ubiquiti",
    "80:2A:A8": "Ubiquiti",
    "9C:05:D6": "Ubiquiti",
    "AC:8B:A9": "Ubiquiti",
    "B4:FB:E4": "Ubiquiti",
    "D0:21:F9": "Ubiquiti",
    "DC:9F:DB": "Ubiquiti",
    "E0:63:DA": "Ubiquiti",
    "E8:63:D0": "Ubiquiti",
    "F0:9F:C2": "Ubiquiti",
    "FC:EC:DA": "Ubiquiti",
    # ── TP-Link ──────────────────────────────────────────────────────
    "00:23:CD": "TP-Link",
    "14:CC:20": "TP-Link",
    "30:B5:C2": "TP-Link",
    "50:C7:BF": "TP-Link",
    "54:C8:0F": "TP-Link",
    "60:E3:27": "TP-Link",
    "78:8C:B5": "TP-Link",
    "98:DA:C4": "TP-Link",
    "B0:4E:26": "TP-Link",
    "C0:C9:E3": "TP-Link",
    "E8:48:B8": "TP-Link",
    "F4:F2:6D": "TP-Link",
    # ── Sonos ────────────────────────────────────────────────────────
    "00:0E:58": "Sonos",
    "34:7E:5C": "Sonos",
    "48:A6:B8": "Sonos",
    "5C:AA:FD": "Sonos",
    "78:28:CA": "Sonos",
    "94:9F:3E": "Sonos",
    "B8:E9:37": "Sonos",
    # ── Roku ──────────────────────────────────────────────────────────
    "00:0D:4B": "Roku",
    "08:05:81": "Roku",
    "20:EF:BD": "Roku",
    "B0:A7:37": "Roku",
    "B8:3E:59": "Roku",
    "CC:6D:A0": "Roku",
    "D8:31:34": "Roku",
    # ── LG Electronics ───────────────────────────────────────────────
    "00:1C:62": "LG Electronics",
    "00:1E:75": "LG Electronics",
    "10:68:3F": "LG Electronics",
    "20:3D:BD": "LG Electronics",
    "34:4D:F7": "LG Electronics",
    "58:A2:B5": "LG Electronics",
    "64:99:5D": "LG Electronics",
    "78:5D:C8": "LG Electronics",
    "88:C9:D0": "LG Electronics",
    "A8:23:FE": "LG Electronics",
    "C4:9A:02": "LG Electronics",
    # ── Sony / PlayStation ───────────────────────────────────────────
    "00:04:1F": "Sony",
    "00:13:A9": "Sony",
    "00:19:C5": "Sony",
    "00:1D:BA": "Sony",
    "28:0D:FC": "Sony",
    "70:9E:29": "Sony",
    "A8:E3:EE": "Sony",
    "FC:0F:E6": "Sony",
    # ── Raspberry Pi Foundation ──────────────────────────────────────
    "28:CD:C1": "Raspberry Pi",
    "B8:27:EB": "Raspberry Pi",
    "D8:3A:DD": "Raspberry Pi",
    "DC:A6:32": "Raspberry Pi",
    "E4:5F:01": "Raspberry Pi",
    # ── Espressif (ESP32 / ESP8266 IoT) ──────────────────────────────
    "08:3A:F2": "Espressif",
    "0C:DC:7E": "Espressif",
    "10:52:1C": "Espressif",
    "24:0A:C4": "Espressif",
    "24:62:AB": "Espressif",
    "24:6F:28": "Espressif",
    "2C:F4:32": "Espressif",
    "30:AE:A4": "Espressif",
    "3C:61:05": "Espressif",
    "3C:71:BF": "Espressif",
    "40:F5:20": "Espressif",
    "48:E7:29": "Espressif",
    "4C:11:AE": "Espressif",
    "54:43:B2": "Espressif",
    "58:CF:79": "Espressif",
    "5C:CF:7F": "Espressif",
    "60:01:94": "Espressif",
    "7C:9E:BD": "Espressif",
    "80:7D:3A": "Espressif",
    "84:0D:8E": "Espressif",
    "84:CC:A8": "Espressif",
    "8C:AA:B5": "Espressif",
    "A0:20:A6": "Espressif",
    "A4:CF:12": "Espressif",
    "AC:67:B2": "Espressif",
    "B4:E6:2D": "Espressif",
    "BC:DD:C2": "Espressif",
    "C4:4F:33": "Espressif",
    "C8:2B:96": "Espressif",
    "CC:50:E3": "Espressif",
    "D8:A0:1D": "Espressif",
    "DC:4F:22": "Espressif",
    "E0:98:06": "Espressif",
    "E8:DB:84": "Espressif",
    "EC:FA:BC": "Espressif",
    "F0:08:D1": "Espressif",
    "F4:CF:A2": "Espressif",
    # ── Tuya / Smart Life IoT ────────────────────────────────────────
    "10:D5:61": "Tuya",
    "50:02:91": "Tuya",
    "68:57:2D": "Tuya",
    "7C:F6:66": "Tuya",
    "84:E3:42": "Tuya",
    "D8:1F:12": "Tuya",
    # ── Ring ──────────────────────────────────────────────────────────
    "34:3E:A4": "Ring",
    "50:14:79": "Ring",
    "9C:76:14": "Ring",
    # ── Wyze ──────────────────────────────────────────────────────────
    "2C:AA:8E": "Wyze",
    "7C:78:B2": "Wyze",
    # ── Philips Hue ──────────────────────────────────────────────────
    "00:17:88": "Philips Hue",
    "EC:B5:FA": "Philips Hue",
    # ── Xiaomi / Roborock ────────────────────────────────────────────
    "04:CF:8C": "Xiaomi",
    "0C:1D:AF": "Xiaomi",
    "10:2A:B3": "Xiaomi",
    "18:59:36": "Xiaomi",
    "28:6C:07": "Xiaomi",
    "34:CE:00": "Xiaomi",
    "3C:BD:3E": "Xiaomi",
    "50:64:2B": "Xiaomi",
    "58:44:98": "Xiaomi",
    "64:CC:2E": "Xiaomi",
    "74:23:44": "Xiaomi",
    "7C:49:EB": "Xiaomi",
    "84:FE:DC": "Xiaomi",
    "8C:DE:F9": "Xiaomi",
    "98:FA:E3": "Xiaomi",
    "A4:77:58": "Xiaomi",
    "AC:C1:EE": "Xiaomi",
    "B0:D5:9D": "Xiaomi",
    "C8:0E:14": "Xiaomi",
    "F0:B4:29": "Xiaomi",
    "F4:F9:51": "Xiaomi",
    "FC:64:BA": "Xiaomi",
    # ── NVIDIA (Shield) ──────────────────────────────────────────────
    "00:04:4B": "Nvidia",
    "48:B0:2D": "Nvidia",
    # ── Lenovo ───────────────────────────────────────────────────────
    "00:06:1B": "Lenovo",
    "28:D2:44": "Lenovo",
    "50:7B:9D": "Lenovo",
    "98:FA:9B": "Lenovo",
    "C8:5B:76": "Lenovo",
    "E8:2A:44": "Lenovo",
    # ── ASUS ─────────────────────────────────────────────────────────
    "00:0C:6E": "ASUS",
    "00:11:D8": "ASUS",
    "00:15:F2": "ASUS",
    "08:60:6E": "ASUS",
    "10:C3:7B": "ASUS",
    "1C:87:2C": "ASUS",
    "2C:56:DC": "ASUS",
    "40:B0:76": "ASUS",
    "54:04:A6": "ASUS",
    # ── Netgear ──────────────────────────────────────────────────────
    "00:09:5B": "Netgear",
    "00:14:6C": "Netgear",
    "00:1E:2A": "Netgear",
    "20:0C:C8": "Netgear",
    "30:46:9A": "Netgear",
    "44:94:FC": "Netgear",
    "6C:B0:CE": "Netgear",
    "84:1B:5E": "Netgear",
    "A4:2B:8C": "Netgear",
    "C4:04:15": "Netgear",
    "E0:91:F5": "Netgear",
    # ── Cisco / Meraki ───────────────────────────────────────────────
    "00:00:0C": "Cisco",
    "00:1A:A1": "Cisco",
    "00:1B:D4": "Cisco",
    "00:24:C4": "Cisco Meraki",
    "0C:8D:DB": "Cisco Meraki",
    "88:15:44": "Cisco Meraki",
    # ── Aruba / HPE Networking ───────────────────────────────────────
    "00:0B:86": "Aruba",
    "00:1A:1E": "Aruba",
    "24:DE:C6": "Aruba",
    "6C:F3:7F": "Aruba",
    "D8:C7:C8": "Aruba",
    # ── Synology ─────────────────────────────────────────────────────
    "00:11:32": "Synology",
    # ── QNAP ─────────────────────────────────────────────────────────
    "00:08:9B": "QNAP",
    "24:5E:BE": "QNAP",
    # ── Nintendo ─────────────────────────────────────────────────────
    "00:09:BF": "Nintendo",
    "00:16:56": "Nintendo",
    "00:17:AB": "Nintendo",
    "00:19:1D": "Nintendo",
    "00:1A:E9": "Nintendo",
    "00:1B:EA": "Nintendo",
    "00:1C:BE": "Nintendo",
    "00:1D:BC": "Nintendo",
    "00:1E:35": "Nintendo",
    "00:1F:32": "Nintendo",
    "00:22:AA": "Nintendo",
    "00:22:D7": "Nintendo",
    "00:23:31": "Nintendo",
    "00:24:F3": "Nintendo",
    "00:25:A0": "Nintendo",
    "2C:10:C1": "Nintendo",
    "34:AF:2C": "Nintendo",
    "40:D2:8A": "Nintendo",
    "58:BD:A3": "Nintendo",
    "78:A2:A0": "Nintendo",
    "7C:BB:8A": "Nintendo",
    "8C:CD:E8": "Nintendo",
    "98:41:5C": "Nintendo",
    "98:B6:E9": "Nintendo",
    "A4:38:CC": "Nintendo",
    "B8:AE:6E": "Nintendo",
    "CC:FB:65": "Nintendo",
    "D8:6B:F7": "Nintendo",
    "E0:0C:7F": "Nintendo",
    "E8:4E:CE": "Nintendo",
    # ── VMware ───────────────────────────────────────────────────────
    "00:0C:29": "VMware",
    "00:50:56": "VMware",
    # ── Realtek (common on cheap IoT / USB adapters) ─────────────────
    "00:E0:4C": "Realtek",
    "48:5B:39": "Realtek",
    "52:54:00": "QEMU/KVM virtual NIC",
    # ── Broadcom ─────────────────────────────────────────────────────
    "00:10:18": "Broadcom",
    # ── Huawei / Honor ───────────────────────────────────────────────
    "00:18:82": "Huawei",
    "00:25:68": "Huawei",
    "04:B0:E7": "Huawei",
    "10:44:00": "Huawei",
    "20:A6:80": "Huawei",
    "48:46:FB": "Huawei",
    "58:2A:F7": "Huawei",
    "70:72:3C": "Huawei",
    "78:F5:57": "Huawei",
    "80:D0:9B": "Huawei",
    "88:53:95": "Huawei",
    "AC:E2:15": "Huawei",
    "C0:70:09": "Huawei",
    "CC:A2:23": "Huawei",
    "D4:6A:A8": "Huawei",
    "F4:C7:14": "Huawei",
    # ── OnePlus ──────────────────────────────────────────────────────
    "94:65:2D": "OnePlus",
    "C0:EE:40": "OnePlus",
    # ── Motorola ─────────────────────────────────────────────────────
    "00:0A:28": "Motorola",
    "40:88:05": "Motorola",
    "68:C4:4D": "Motorola",
    "7C:46:85": "Motorola",
    "E8:91:20": "Motorola",
    # ── Tesla ────────────────────────────────────────────────────────
    "04:D3:B0": "Tesla",
    "4C:FC:AA": "Tesla",
    # ── ecobee ───────────────────────────────────────────────────────
    "44:61:32": "ecobee",
    # ── Wemo / Belkin ────────────────────────────────────────────────
    "00:17:3F": "Belkin",
    "08:86:3B": "Belkin (Wemo)",
    "58:EF:68": "Belkin (Wemo)",
    "94:10:3E": "Belkin (Wemo)",
    "C4:12:F5": "Belkin (Wemo)",
    "EC:1A:59": "Belkin (Wemo)",
    # ── Yale / August ────────────────────────────────────────────────
    "00:1A:22": "Yale / August",
    # ── Shelly ───────────────────────────────────────────────────────
    "3C:61:05": "Shelly / Espressif",
    "E8:DB:84": "Shelly / Espressif",
    # ── Lutron ───────────────────────────────────────────────────────
    "00:0C:C1": "Lutron",
    "00:17:9A": "Lutron",
    # ══════════════════════════════════════════════════════════════════
    #  SURVEILLANCE CAMERAS & DVR/NVR VENDORS
    #  (primary targets for the blocker)
    # ══════════════════════════════════════════════════════════════════
    # ── Hikvision / HiWatch ──────────────────────────────────────────
    "00:0E:DB": "Hikvision",
    "10:12:FB": "Hikvision",
    "18:68:CB": "Hikvision",
    "1C:C3:16": "Hikvision",
    "24:28:FD": "Hikvision",
    "28:57:BE": "Hikvision",
    "2C:A5:9C": "Hikvision",
    "34:E8:94": "Hikvision",
    "38:AF:29": "Hikvision",
    "44:47:CC": "Hikvision",
    "48:AD:08": "Hikvision",
    "4C:BD:8F": "Hikvision",
    "54:C4:15": "Hikvision",
    "58:03:FB": "Hikvision",
    "5C:E0:CA": "Hikvision",
    "64:A4:00": "Hikvision",
    "6C:EF:C6": "Hikvision",
    "74:DA:88": "Hikvision",
    "7C:46:D2": "Hikvision",
    "80:A4:47": "Hikvision",
    "88:40:3B": "Hikvision",
    "8C:E7:48": "Hikvision",
    "94:E1:AC": "Hikvision",
    "A0:3E:6B": "Hikvision",
    "A4:14:37": "Hikvision",
    "A8:62:A2": "Hikvision",
    "B0:68:E6": "Hikvision",
    "B4:A3:82": "Hikvision",
    "BC:AD:28": "Hikvision",
    "C0:5C:20": "Hikvision",
    "C0:56:E3": "Hikvision",
    "C4:2F:90": "Hikvision",
    "C8:02:8F": "Hikvision",
    "CC:D3:9D": "Hikvision",
    "D4:43:0E": "Hikvision",
    "D8:AF:3B": "Hikvision",
    "DC:80:84": "Hikvision",
    "E0:1C:FD": "Hikvision",
    "E0:AB:FE": "Hikvision",
    "E4:24:6C": "Hikvision",
    "EC:8E:B5": "Hikvision",
    "F4:5E:47": "Hikvision",
    "F8:4D:FC": "Hikvision",
    # ── Dahua ────────────────────────────────────────────────────────
    "00:19:48": "Dahua",
    "0C:E6:00": "Dahua",
    "10:01:2C": "Dahua",
    "14:A7:8B": "Dahua",
    "18:93:7F": "Dahua",
    "1C:C5:64": "Dahua",
    "20:17:42": "Dahua",
    "24:29:34": "Dahua",
    "28:AD:3E": "Dahua",
    "2C:99:24": "Dahua",
    "34:DA:B7": "Dahua",
    "38:AF:D7": "Dahua",
    "3C:EF:8C": "Dahua",
    "40:F4:13": "Dahua",
    "48:33:DD": "Dahua",
    "4C:11:BF": "Dahua",
    "54:2B:DE": "Dahua",
    "58:11:22": "Dahua",
    "60:FD:56": "Dahua",
    "68:A4:0E": "Dahua",
    "70:E1:D4": "Dahua",
    "74:1A:E0": "Dahua",
    "80:2D:BF": "Dahua",
    "84:9A:40": "Dahua",
    "A0:BD:1D": "Dahua",
    "A4:8C:47": "Dahua",
    "B0:60:88": "Dahua",
    "B4:A3:15": "Dahua",
    "C8:F5:D6": "Dahua",
    "D4:43:A8": "Dahua",
    "E0:50:8B": "Dahua",
    "E4:81:B3": "Dahua",
    "F8:4F:AD": "Dahua",
    # ── Reolink ──────────────────────────────────────────────────────
    "58:72:D4": "Reolink",
    "B4:6D:C2": "Reolink",
    "EC:71:DB": "Reolink",
    "9C:8E:CD": "Reolink",
    # ── Amcrest / Foscam ─────────────────────────────────────────────
    "00:62:6E": "Amcrest",
    "C0:3C:04": "Foscam",
    # ── XMEye / Xiongmai (XM) ────────────────────────────────────────
    "00:12:12": "XMEye/Xiongmai",
    "00:12:13": "XMEye/Xiongmai",
    "00:12:14": "XMEye/Xiongmai",
    "00:12:15": "XMEye/Xiongmai",
    "00:12:16": "XMEye/Xiongmai",
    "00:12:17": "XMEye/Xiongmai",
    "00:12:41": "XMEye/Xiongmai",
    "00:12:42": "XMEye/Xiongmai",
    "E0:62:90": "XMEye/Xiongmai",
    # ── Uniview ──────────────────────────────────────────────────────
    "24:16:6D": "Uniview",
    "68:61:54": "Uniview",
    "A0:CF:2B": "Uniview",
    # ── TP-Link VIGI (cameras) ───────────────────────────────────────
    "54:AF:97": "TP-Link VIGI",
    "74:FE:CE": "TP-Link VIGI",
    # ── Axis Communications ──────────────────────────────────────────
    "00:40:8C": "Axis",
    "AC:CC:8E": "Axis",
    "B8:A4:4F": "Axis",
    # ── Vivotek ──────────────────────────────────────────────────────
    "00:02:D1": "Vivotek",
    "00:22:CF": "Vivotek",
    # ── Hanwha (Samsung Techwin) ─────────────────────────────────────
    "00:09:18": "Hanwha/Samsung Techwin",
    "00:16:6C": "Hanwha/Samsung Techwin",
    "9C:43:1E": "Hanwha/Samsung Techwin",
    # ── EZVIZ (Hikvision consumer) ───────────────────────────────────
    "28:29:86": "EZVIZ",
    "48:C8:62": "EZVIZ",
    "60:F4:3A": "EZVIZ",
    "C4:1E:CE": "EZVIZ",
    # ── Imou (Dahua consumer) ────────────────────────────────────────
    "7C:14:76": "Imou",
    "AC:3B:77": "Imou",
    # ── Annke ────────────────────────────────────────────────────────
    "00:01:F0": "Annke",
    # ── Lorex ────────────────────────────────────────────────────────
    "00:40:3B": "Lorex",
    # ── Swann ────────────────────────────────────────────────────────
    "00:A1:D8": "Swann",
    # ── Eufy Security ────────────────────────────────────────────────
    "98:8B:0A": "Eufy",
    "FC:D7:49": "Eufy",
    # ── Wyze Cam (already partial above, add more) ───────────────────
    "2C:AA:8E": "Wyze",
    "7C:78:B2": "Wyze",
    "A4:DA:22": "Wyze",
    # ── YI Technology ────────────────────────────────────────────────
    "78:A5:04": "YI Technology",
    # ── Wansview ─────────────────────────────────────────────────────
    "18:BA:A6": "Wansview",
    # ── Hiseeu ───────────────────────────────────────────────────────
    "C8:E7:F0": "Hiseeu",
    # ── Zosi ─────────────────────────────────────────────────────────
    "38:D5:47": "Zosi",
    # ══════════════════════════════════════════════════════════════════
    #  CAMERA CHIP MANUFACTURERS & WHITE-LABEL ODMs
    #  These make the SoC/board inside most cheap cameras.
    #  A device with these OUIs that has no hostname is very likely
    #  a camera or DVR.
    # ══════════════════════════════════════════════════════════════════
    # ── HiSilicon (Huawei chip subsidiary — in MOST cheap cameras) ──
    "00:0A:DB": "HiSilicon",
    "00:18:82": "HiSilicon",
    "00:1E:73": "HiSilicon",
    "00:22:A0": "HiSilicon",
    "00:46:4B": "HiSilicon",
    "08:E5:DA": "HiSilicon",
    "10:27:F5": "HiSilicon",
    "14:B3:1F": "HiSilicon",
    "20:F4:1B": "HiSilicon",
    "28:76:CD": "HiSilicon",
    "34:A3:BF": "HiSilicon",
    "40:F3:85": "HiSilicon",
    "48:FD:8E": "HiSilicon",
    "4C:6B:E8": "HiSilicon",
    "54:A6:19": "HiSilicon",
    "5C:FA:FB": "HiSilicon",
    "60:DE:44": "HiSilicon",
    "70:B3:D5": "HiSilicon",
    "74:69:4A": "HiSilicon",
    "78:32:1B": "HiSilicon",
    "80:9F:AB": "HiSilicon",
    "88:CE:FA": "HiSilicon",
    "8C:E1:17": "HiSilicon",
    "94:C6:91": "HiSilicon",
    "98:6C:3D": "HiSilicon",
    "A4:A8:0F": "HiSilicon",
    "AC:B7:4F": "HiSilicon",
    "B0:41:1D": "HiSilicon",
    "BC:34:00": "HiSilicon",
    "C4:F0:81": "HiSilicon",
    "CC:B8:A8": "HiSilicon",
    "D0:48:E7": "HiSilicon",
    "D4:67:E7": "HiSilicon",
    "E0:24:7F": "HiSilicon",
    "E8:6F:38": "HiSilicon",
    "F4:C7:14": "HiSilicon",
    # ── Ingenic (T-series SoC in budget cameras) ────────────────────
    "00:13:EF": "Ingenic",
    "54:B8:0A": "Ingenic",
    # ── SigmaStar (MStar — camera SoC) ──────────────────────────────
    "00:0C:E5": "SigmaStar",
    # ── Novatek (camera SoC / dashcam chips) ────────────────────────
    "00:0E:C6": "Novatek",
    # ── Grain Media (camera SoC) ────────────────────────────────────
    "00:19:E0": "GrainMedia",
    # ── Generic Chinese camera brands / white-label ─────────────────
    "00:15:6D": "Sunell",
    "00:1A:07": "Sunell",
    "18:AF:61": "Sunell",
    "00:0B:82": "Grandstream",
    "00:0B:46": "TVT Digital",
    "00:01:C0": "Provision-ISR",
    "00:1B:54": "Provision-ISR",
    "00:30:6E": "Milesight",
    "28:F3:66": "Milesight",
    "70:B3:17": "Milesight",
    "C0:51:7E": "Tiandy",
    "60:81:2B": "Tiandy",
    "58:E8:76": "TVT Digital",
    "00:06:39": "Kedacom",
    "00:50:A0": "Kedacom",
    "00:18:AE": "TVT Digital",
    "00:40:48": "Geovision",
    "00:13:E2": "Geovision",
    "00:23:53": "Geovision",
    "00:1D:C9": "Geovision",
    "BC:51:FE": "Dericam",
    "78:44:FD": "TP-Link (camera)",
    "00:1E:B4": "ACTI",
    "00:0F:7C": "ACTI",
    # ── Additional Hikvision OUIs (recent allocations) ──────────────
    "14:97:20": "Hikvision",
    "44:19:B6": "Hikvision",
    "4C:E9:E4": "Hikvision",
    "50:DE:19": "Hikvision",
    "60:08:10": "Hikvision",
    "68:E2:09": "Hikvision",
    "70:52:72": "Hikvision",
    "78:17:BE": "Hikvision",
    "7C:09:4E": "Hikvision",
    "84:E3:27": "Hikvision",
    "90:02:A9": "Hikvision",
    "98:DF:82": "Hikvision",
    "A0:5C:B6": "Hikvision",
    "A4:56:30": "Hikvision",
    "B4:A3:82": "Hikvision",
    "C0:5B:2B": "Hikvision",
    "D4:B1:08": "Hikvision",
    "E0:50:8B": "Hikvision",
    "EC:94:D5": "Hikvision",
    "F0:C4:2F": "Hikvision",
    # ── Additional Dahua OUIs ────────────────────────────────────────
    "00:1A:6B": "Dahua",
    "04:11:19": "Dahua",
    "0C:E3:2B": "Dahua",
    "14:27:12": "Dahua",
    "1C:B0:94": "Dahua",
    "2C:9D:1E": "Dahua",
    "3C:DA:2A": "Dahua",
    "44:6A:2E": "Dahua",
    "4C:07:C9": "Dahua",
    "58:10:8C": "Dahua",
    "64:66:24": "Dahua",
    "6C:1C:71": "Dahua",
    "78:A8:73": "Dahua",
    "80:37:3E": "Dahua",
    "88:E0:56": "Dahua",
    "90:F7:2F": "Dahua",
    "9C:14:63": "Dahua",
    "A8:48:FA": "Dahua",
    "BC:32:5F": "Dahua",
    "C8:D7:B0": "Dahua",
    "DC:F8:B9": "Dahua",
    "E4:57:40": "Dahua",
    "F8:6E:CF": "Dahua",
    # ── Additional Reolink OUIs ──────────────────────────────────────
    "24:2F:D0": "Reolink",
    "3C:A3:08": "Reolink",
    "74:EE:2A": "Reolink",
    "DC:23:4E": "Reolink",
    # ── Additional XMEye / Xiongmai ──────────────────────────────────
    "00:12:18": "XMEye/Xiongmai",
    "00:12:19": "XMEye/Xiongmai",
    "00:12:20": "XMEye/Xiongmai",
    "00:12:21": "XMEye/Xiongmai",
    "00:12:22": "XMEye/Xiongmai",
    "00:12:23": "XMEye/Xiongmai",
    "00:12:24": "XMEye/Xiongmai",
    "00:12:25": "XMEye/Xiongmai",
    "00:12:26": "XMEye/Xiongmai",
    "00:12:27": "XMEye/Xiongmai",
    "00:12:28": "XMEye/Xiongmai",
    "00:12:29": "XMEye/Xiongmai",
    "00:12:30": "XMEye/Xiongmai",
    "00:12:31": "XMEye/Xiongmai",
    "00:12:32": "XMEye/Xiongmai",
    "00:12:33": "XMEye/Xiongmai",
    "00:12:34": "XMEye/Xiongmai",
    "00:12:35": "XMEye/Xiongmai",
}


# Vendors that manufacture surveillance cameras.  Used by the suspicious
# traffic analyzer to flag camera-like devices automatically.
# Vendors that ARE camera manufacturers (high confidence).
CAMERA_VENDORS: set[str] = {
    "Hikvision", "Dahua", "Reolink", "Amcrest", "Foscam",
    "XMEye/Xiongmai", "Uniview", "TP-Link VIGI", "Axis", "Vivotek",
    "Hanwha/Samsung Techwin", "EZVIZ", "Imou", "Annke", "Lorex",
    "Swann", "Eufy", "Wyze", "YI Technology", "Wansview", "Hiseeu",
    "Zosi", "Ring", "Sunell", "TVT Digital", "Provision-ISR",
    "Milesight", "Tiandy", "Kedacom", "Geovision", "Dericam",
    "TP-Link (camera)", "ACTI", "Grandstream",
}

# Vendors that make camera CHIPS — device is PROBABLY a camera
# but could be another embedded device. Need port scan to confirm.
CAMERA_CHIP_VENDORS: set[str] = {
    "HiSilicon", "Ingenic", "SigmaStar", "Novatek", "GrainMedia",
}

# Hostname patterns commonly seen on IP cameras.
CAMERA_HOSTNAME_PATTERNS: list[str] = [
    "ipc",
    "ipcam",
    "camera",
    "cam",
    "dvr",
    "nvr",
    "hikvision",
    "dahua",
    "dh-",
    "ds-",        # Hikvision model prefix
    "ipc-",       # Dahua model prefix
    "reolink",
    "amcrest",
    "foscam",
    "xmeye",
    "ezviz",
    "imou",
]


def lookup_vendor(mac: str) -> str:
    """Return the vendor name for a MAC address, or 'Unknown'."""
    prefix = mac.upper().replace("-", ":")[0:8]
    return _OUI_TABLE.get(prefix, "Unknown")


def lookup_vendor_safe(mac: str | None) -> str:
    """Return the vendor for *mac*, tolerating ``None``."""
    if not mac:
        return "Unknown"
    return lookup_vendor(mac)


# Keywords that indicate a camera vendor when found ANYWHERE in the
# vendor/OUI string (case-insensitive). Catches UniFi's long-form OUI
# strings like "Hangzhou Hikvision Digital Technology Co.,Ltd."
CAMERA_VENDOR_KEYWORDS: list[str] = [
    "hikvision", "dahua", "reolink", "amcrest", "foscam", "xiongmai",
    "xmeye", "uniview", "axis", "vivotek", "hanwha", "techwin",
    "ezviz", "imou", "annke", "lorex", "swann", "eufy", "wyze",
    "yi technology", "wansview", "hiseeu", "zosi", "sunell", "tvt",
    "provision", "milesight", "tiandy", "kedacom", "geovision",
    "dericam", "acti", "grandstream", "hisilicon", "ingenic",
    "sigmastar", "novatek", "grainmedia", "vigi", "ring",
    "camera", "ipcam", "ip cam", "nvr", "dvr", "surveillance",
]


def is_camera_vendor(vendor: str) -> bool:
    """Return True if *vendor* matches any known camera manufacturer.

    Uses fuzzy matching — checks if any camera keyword appears anywhere
    in the vendor string (case-insensitive). This catches UniFi's
    long-form OUI strings like 'Hangzhou Hikvision Digital Technology'.
    """
    if not vendor or vendor == "Unknown":
        return False
    # Exact match first (fast path).
    if vendor in CAMERA_VENDORS or vendor in CAMERA_CHIP_VENDORS:
        return True
    # Fuzzy match — keyword anywhere in vendor string.
    vendor_lower = vendor.lower()
    return any(kw in vendor_lower for kw in CAMERA_VENDOR_KEYWORDS)


def is_camera_like(mac: str, hostname: str = "", vendor: str = "") -> bool:
    """Return True if the device looks like an IP camera.

    Checks vendor OUI (fuzzy), hostname patterns, and MAC lookup.
    """
    if not vendor:
        vendor = lookup_vendor_safe(mac)
    if is_camera_vendor(vendor):
        return True
    hn = hostname.lower()
    return any(pat in hn for pat in CAMERA_HOSTNAME_PATTERNS)
